
import FooterThreeCols from './Footer/FooterThreeCols'
import { CartProvider } from './IDContext/CartProvider'
import Navbar from './Navbar/Navbar'
import { Toaster } from 'react-hot-toast';
import './globals.css'
import { UserProvider } from './IDContext/UserProvider';
import QueryProvider from './QueryProvider';



export const metadata = {
  title: 'E-commerce-web-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <CartProvider>
            <UserProvider>
              <Navbar />
              {children}
              <Toaster />
              <FooterThreeCols />
            </UserProvider>
          </CartProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
